### ISSUE TITLE
Generating amazon cookie [Help]

### ISSUE THREAD

**Issue by tuner007** [mayaxcn/Amazon-cookie-loader#1]
Is there a way to generate cookies by using just amazon id and password. 
If not, can we extract it while logged in our browser using some script.

Actually, i want to add amazon product to my cart using python script. 

Thanks!

**Comment by mayaxcn** [comment]
You can use "Editthiscookie" in Chrome tool to save your logined cookies in JSON string.
If your want to "add amazon product to the cart", you can use SELEUIM by python script and achieve this function.

**Comment by mayaxcn** [comment]
> Is there a way to generate cookies by using just amazon id and password.
> If not, can we extract it while logged in our browser using some script.
> 
> Actually, i want to add amazon product to my cart using python script.
> 
> Thanks!

You can use "Editthiscookie" in Chrome tool to save your logined cookies in JSON string.
If your want to "add amazon product to the cart", you can use "selenium" by python script and achieve this function.

**Comment by tuner007** [comment]
> > Is there a way to generate cookies by using just amazon id and password.
> > If not, can we extract it while logged in our browser using some script.
> 
> You can use "Editthiscookie" in Chrome tool to save your logined cookies in JSON string.
> If your want to "add amazon product to the cart", you can use "selenium" by python script and achieve this function.

Thanks for instant response! 

i can now extract cookies using browser while logged in.
Selenium is slow and takes time, i was looking for a better solution.
 
Thanks!
