### ISSUE TITLE
Amazon Cookie

### ISSUE THREAD

**Issue by Armta** [mayaxcn/Amazon-cookie-loader#2]
联系你

**Comment by mayaxcn** [comment]
留个微信我加你？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mayaxcn/Amazon-cookie-loader"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 下午4:42
收件人:&nbsp;"mayaxcn/Amazon-cookie-loader"<Amazon-cookie-loader@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[mayaxcn/Amazon-cookie-loader] Amazon Cookie (#2)





 
需要亚马逊Cookie,怎么联系你

**Comment by Armta** [comment]
dgdexinrong

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: maYax.Liu<mailto:notifications@github.com>
发送时间: 2020年11月24日 16:54
收件人: mayaxcn/Amazon-cookie-loader<mailto:Amazon-cookie-loader@noreply.github.com>
抄送: Armta<mailto:dingnianxing@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [mayaxcn/Amazon-cookie-loader] Amazon Cookie (#2)

留个微信我加你？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mayaxcn/Amazon-cookie-loader" <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 下午4:42
收件人:&nbsp;"mayaxcn/Amazon-cookie-loader"<Amazon-cookie-loader@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[mayaxcn/Amazon-cookie-loader] Amazon Cookie (#2)






需要亚马逊Cookie,怎么联系你

―
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―
