### ISSUE TITLE
你好我需要更多的amazon黑科技

### ISSUE THREAD

**Issue by Peng-haowu** [mayaxcn/Amazon-cookie-loader#3]
请问怎么联系你
------------------------
站内消息即可

**Comment by a725970** [comment]
请问怎么联系你
-----------------
站内消息即可

**Comment by mayaxcn** [comment]
> 

在这联系即可

**Comment by Peng-haowu** [comment]
> 

我需要获取亚马逊cookie的软件工具请问可以开发吗？

**Comment by mayaxcn** [comment]
只有现成已经采集好的cookie，不提供采集工具

**Comment by lipeng897** [comment]
你好，有telegram么？发一下联系一下
